var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},g="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");g=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?g=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(g=document.currentScript.src),g=g.startsWith("blob:")?"":g.substr(0,g.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ma=f.print||console.log.bind(console),n=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var na=f.wasmBinary,oa,q=!1,pa,r,t,qa,ra,u,w,sa,x;
function ta(){var a=oa.buffer;f.HEAP8=r=new Int8Array(a);f.HEAP16=qa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=ra=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=w=new Uint32Array(a);f.HEAPF32=sa=new Float32Array(a);f.HEAPF64=x=new Float64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ua.unshift(a)}var y=0,za=null,z=null;
function Aa(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Ca;function Da(a){if(a==Ca&&na)return new Uint8Array(na);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Ea(a){return na?Promise.resolve().then(()=>Da(a)):ia(a).then(b=>new Uint8Array(b),()=>Da(a))}
function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{n(`failed to asynchronously prepare wasm: ${d}`);Aa(d)})}function Ga(a,b){var c=Ca;na||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||la(c)||ca||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){n(`wasm streaming compile failed: ${e}`);n("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}
class Ha{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ia=a=>{for(;0<a.length;)a.shift()(f)},Ja=f.noExitRuntime||!0,Ka=0,La="undefined"!=typeof TextDecoder?new TextDecoder:void 0,A=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&La)return La.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|h:(e&7)<<18|k<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},C={},Ma=a=>{a instanceof Ha||"unwind"==a||ha(1,a)},Na=a=>{pa=a;Ja||0<Ka||(f.onExit?.(a),q=!0);ha(a,new Ha(a))},Oa=a=>{pa=a;Na(a)},Pa=()=>{if(!(Ja||0<Ka))try{var a=pa;pa=a;Na(a)}catch(b){Ma(b)}},Qa=a=>{if(!q)try{a(),Pa()}catch(b){Ma(b)}},Xa=(a,b)=>{Ra=a;Sa=b;if(D)if(Ta||=!0,0==a)E=function(){setTimeout(F,Math.max(0,Ua+b-performance.now())|0)};else if(1==a)E=function(){Va(F)};else if(2==a){if("undefined"==typeof Wa)if("undefined"==typeof setImmediate){var c=
[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Wa=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Wa=setImmediate;E=function(){Wa(F)}}},fb=(a,b,c,d,e)=>{function k(){return h<Ya?(Pa(),!1):!0}D=a;Za=d;var h=Ya;Ta=!1;F=function(){if(!q)if(0<$a.length){var l=$a.shift();l.vd(l.ld);if(ab){var m=ab,
p=0==m%1?m-1:Math.floor(m);ab=l.nd?p:(8*m+(p+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",m=ab??0,p=bb.td??0,m?m<p?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));k()&&setTimeout(F,0)}else if(k())if(cb=cb+1|0,1==Ra&&1<Sa&&0!=cb%Sa)E();else{0==Ra&&(Ua=performance.now());a:if(!q){for(l of db)if(!1===l())break a;Qa(a);for(m of eb)m()}k()&&E()}};e||(b&&0<b?Xa(0,1E3/b):Xa(1,1),E());if(c)throw"unwind";},Ta=!1,E=null,Ya=0,D=null,Za=0,Ra=0,Sa=0,cb=
0,$a=[],db=[],eb=[];function gb(){E=null;Ya++}var G=0;function Va(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===G)G=b+1E3/60;else for(;b+2>=G;)G+=1E3/60;setTimeout(a,Math.max(G-b,0))}}var bb={},Ua,F,Wa,ab;function hb(a){var b=H.jc[a];b.target.removeEventListener(b.ic,b.Mc,b.kc);H.jc.splice(a,1)}function ib(){if(navigator.userActivation?navigator.userActivation.isActive:H.Ac&&H.ad.yc){var a=H.pc;H.pc=[];for(var b of a)b.Dc(...b.Ic)}}
function I(a){if(!a.target)return-4;if(a.lc)a.Mc=function(c){++H.Ac;H.ad=a;ib();a.mc(c);ib();--H.Ac},a.target.addEventListener(a.ic,a.Mc,a.kc),H.jc.push(a);else for(var b=0;b<H.jc.length;++b)H.jc[b].target==a.target&&H.jc[b].ic==a.ic&&hb(b--);return 0}function jb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={md:0,wd:0,Bc:0,wc:0,Hc:0,Fc:0,zc:0,rd:0,zd:0,qd:0,ud:0,Cc:0,Kd:0,Ec:0,Bd(){for(;H.jc.length;)hb(H.jc.length-1);H.pc=[]},Ac:0,pc:[],pd(a,b,c){function d(k,h){if(k.length!=h.length)return!1;for(var l in k)if(k[l]!=h[l])return!1;return!0}for(var e of H.pc)if(e.Dc==a&&d(e.Ic,c))return;H.pc.push({Dc:a,Sc:b,Ic:c});H.pc.sort((k,h)=>k.Sc<h.Sc)},Dd(a){H.pc=H.pc.filter(b=>b.Dc!=a)},jc:[],Cd:(a,b)=>{for(var c=0;c<H.jc.length;++c)H.jc[c].target!=a||b&&b!=H.jc[c].ic||hb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||
document.webkitFullscreenEnabled}},kb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],J=a=>{a=2<a?a?A(t,a):"":a;return kb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},lb=a=>0>kb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},mb=[],nb,K=a=>{var b=mb[a];b||(a>=mb.length&&(mb.length=a+1),mb[a]=b=nb.get(a));return b},L=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var h=a.charCodeAt(k);if(55296<=h&&57343>=
h){var l=a.charCodeAt(++k);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(b>=c)break;d[b++]=h}else{if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=128|h>>6&63}d[b++]=128|h&63}}d[b]=0;return b-e},ob=(a,b,c,d,e,k)=>{H.zc||(H.zc=M(256));a={target:J(a),ic:k,lc:d,mc:(h=event)=>{var l=h.target.id?h.target.id:"",m=H.zc;L(jb(h.target),m+0,128);L(l,m+128,128);K(d)(e,m,b)&&h.preventDefault()},kc:c};
return I(a)},pb=(a,b,c,d,e,k)=>{H.Bc||(H.Bc=M(160));a={target:J(a),ic:k,lc:d,mc:h=>{var l=H.Bc;x[l>>3]=h.timeStamp;var m=l>>2;u[m+2]=h.location;r[l+12]=h.ctrlKey;r[l+13]=h.shiftKey;r[l+14]=h.altKey;r[l+15]=h.metaKey;r[l+16]=h.repeat;u[m+5]=h.charCode;u[m+6]=h.keyCode;u[m+7]=h.which;L(h.key||"",l+32,32);L(h.code||"",l+64,32);L(h.char||"",l+96,32);L(h.locale||"",l+128,32);K(d)(e,l,b)&&h.preventDefault()},kc:c};return I(a)},qb=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;
u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;qa[2*d+14]=b.button;qa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=lb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,k)=>{H.wc||(H.wc=M(64));a=J(a);return I({target:a,yc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,ic:k,lc:d,mc:(h=event)=>{qb(H.wc,h,a);K(d)(e,H.wc,b)&&h.preventDefault()},kc:c})},rb=(a,b,c,d,e)=>{H.Cc||(H.Cc=M(257));return I({target:a,
ic:e,lc:d,mc:(k=event)=>{var h=H.Cc,l=document.pointerLockElement||document.qc||document.Pc||document.Nc;r[h]=!!l;var m=l?.id||"";L(jb(l),h+1,128);L(m,h+129,128);K(d)(20,h,b)&&k.preventDefault()},kc:c})},sb=(a,b,c,d,e)=>I({target:a,ic:e,lc:d,mc:(k=event)=>{K(d)(38,0,b)&&k.preventDefault()},kc:c}),tb=(a,b,c,d)=>{H.Fc||(H.Fc=M(36));a=J(a);return I({target:a,ic:"resize",lc:d,mc:(e=event)=>{if(e.target==a){var k=document.body;if(k){var h=H.Fc;u[h>>2]=0;u[h+4>>2]=k.clientWidth;u[h+8>>2]=k.clientHeight;
u[h+12>>2]=innerWidth;u[h+16>>2]=innerHeight;u[h+20>>2]=outerWidth;u[h+24>>2]=outerHeight;u[h+28>>2]=pageXOffset|0;u[h+32>>2]=pageYOffset|0;K(d)(10,h,b)&&e.preventDefault()}}},kc:c})},ub=(a,b,c,d,e,k)=>{H.Ec||(H.Ec=M(1552));a=J(a);return I({target:a,yc:"touchstart"==k||"touchend"==k,ic:k,lc:d,mc:h=>{var l={},m=h.touches;for(var p of m)p.Oc=p.Rc=0,l[p.identifier]=p;for(var v of h.changedTouches)v.Oc=1,l[v.identifier]=v;for(var N of h.targetTouches)l[N.identifier].Rc=1;m=H.Ec;x[m>>3]=h.timeStamp;r[m+
12]=h.ctrlKey;r[m+13]=h.shiftKey;r[m+14]=h.altKey;r[m+15]=h.metaKey;p=m+16;v=lb(a);N=0;for(let B of Object.values(l))if(l=p>>2,u[l]=B.identifier,u[l+1]=B.screenX,u[l+2]=B.screenY,u[l+3]=B.clientX,u[l+4]=B.clientY,u[l+5]=B.pageX,u[l+6]=B.pageY,r[p+28]=B.Oc,r[p+29]=B.Rc,u[l+8]=B.clientX-(v.left|0),u[l+9]=B.clientY-(v.top|0),p+=48,31<++N)break;u[m+8>>2]=N;K(d)(e,m,b)&&h.preventDefault()},kc:c})},P,vb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,
d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,h)=>b.drawElementsInstancedANGLE(c,d,e,k,h))},wb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},xb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},yb=a=>
{a.sd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},zb=a=>{a.xd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Ab=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Bb=1,Q=[],R=[],Cb=[],S=[],T=[],U=[],Db=[],Eb=[],V=[],Fb={},Gb=4,Hb=0,Ib=a=>{for(var b=Bb++,c=a.length;c<b;c++)a[c]=null;return b},X=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=P[c](),h=k&&Ib(d);k?(k.name=h,d[h]=k):W||=1282;u[b+4*e>>2]=h}},Kb=(a,b)=>{a.qc||(a.qc=a.getContext,a.getContext=function(d,e){e=a.qc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Qc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Jb(c,b):0},Jb=(a,b)=>{var c=Ib(Eb),d={handle:c,attributes:b,version:b.Qc,xc:a};a.canvas&&(a.canvas.kd=d);Eb[c]=d;("undefined"==typeof b.Lc||b.Lc)&&Lb(d);return c},Lb=a=>{a||=Y;if(!a.gd){a.gd=!0;var b=a.xc;b.hd=b.getExtension("WEBGL_multi_draw");b.ed=b.getExtension("EXT_polygon_offset_clamp");b.dd=b.getExtension("EXT_clip_control");b.jd=b.getExtension("WEBGL_polygon_mode");vb(b);wb(b);xb(b);yb(b);zb(b);2<=a.version&&(b.Kc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Kc)b.Kc=
b.getExtension("EXT_disjoint_timer_query");Ab(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},W,Y,Mb=(a,b,c,d,e,k)=>{a={target:J(a),ic:k,lc:d,mc:(h=event)=>{K(d)(e,0,b)&&h.preventDefault()},kc:c};I(a)},Nb=(a,b,c,d)=>{H.Hc||(H.Hc=M(96));return I({target:a,yc:!0,ic:"wheel",lc:d,mc:(e=event)=>{var k=H.Hc;qb(k,e,a);x[k+64>>3]=e.deltaX;x[k+72>>3]=e.deltaY;x[k+80>>3]=e.deltaZ;u[k+88>>2]=e.deltaMode;K(d)(9,k,b)&&e.preventDefault()},kc:c})},Ob=["default","low-power",
"high-performance"],Pb=[null,[],[]],Qb=[];function Rb(){var a=Ab(P);return a=a.concat(a.map(b=>"GL_"+b))}
var Sb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){W||=1282;return}c=Rb().length;break;case 33307:case 33308:if(2>Y.version){W||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:W||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:W||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else W||=1281},Tb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ub=a=>{var b=Tb(a)+1,c=M(b);c&&L(a,c,b);return c},Vb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Wb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?qa:4==a?u:6==a?sa:5==a||28922==a||28520==a||30779==a||30782==a?w:ra},Xb=(a,b,c,d,e)=>{a=Wb(a);b=d*((Hb||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Gb-1&-Gb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Zb=a=>{var b=Tb(a)+1,c=Yb(b);L(a,c,b);return c},bc=a=>{var b=$b();a();ac(b)};f.requestAnimationFrame=Va;f.pauseMainLoop=gb;f.resumeMainLoop=function(){Ya++;var a=Ra,b=Sa,c=D;D=null;fb(c,0,!1,Za,!0);Xa(a,b);E()};f.preMainLoop&&db.push(f.preMainLoop);f.postMainLoop&&eb.push(f.postMainLoop);for(var cc=0;32>cc;++cc)Qb.push(Array(cc));
var oc={nb:()=>{Aa("")},jb:(a,b,c)=>t.copyWithin(a,b,b+c),fb:()=>{Ja=!1;Ka=0},ib:a=>{if(ca){if(!a)return 1;a=a?A(t,a):"";if(!a.length)return 0;a=require("child_process").Id(a,[],{Fd:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return null===a.status?b(0,(c=>{switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15;default:return 2}})(a.signal)):a.status<<8|0}return a?-52:0},gb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),
delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Qa(()=>dc(a,performance.now()))},b);C[a]={id:c,Jd:b};return 0},Ta:()=>{gb();D=null},ca:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ea:(a,b,c)=>{a=J(a);if(!a)return-4;a=lb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Ua:()=>performance.now(),_a:(a,b)=>{function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},hb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+
.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);ta();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},M:(a,b,c,d)=>ob(a,b,c,d,12,"blur"),ba:(a,b,c)=>{a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:(a,b,c,d)=>ob(a,b,c,d,13,"focus"),W:(a,b,c,d)=>pb(a,b,c,d,2,"keydown"),U:(a,b,c,d)=>pb(a,b,c,d,1,"keypress"),V:(a,b,c,d)=>pb(a,b,c,d,3,"keyup"),$a:(a,b,c)=>{a=K(a);fb(a,b,c)},aa:(a,b,c,d)=>
O(a,b,c,d,5,"mousedown"),Z:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),Y:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),_:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),$:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),P:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.qc||document.body.Pc||document.body.Nc))return-1;a=J(a);if(!a)return-4;rb(a,b,c,d,"mozpointerlockchange");rb(a,b,c,d,"webkitpointerlockchange");rb(a,b,c,d,"mspointerlockchange");return rb(a,b,c,d,"pointerlockchange")},O:(a,b,c,d)=>
{if(!document||!(document.body.requestPointerLock||document.body.qc||document.body.Pc||document.body.Nc))return-1;a=J(a);if(!a)return-4;sb(a,b,c,d,"mozpointerlockerror");sb(a,b,c,d,"webkitpointerlockerror");sb(a,b,c,d,"mspointerlockerror");return sb(a,b,c,d,"pointerlockerror")},da:(a,b,c,d)=>tb(a,b,c,d),Q:(a,b,c,d)=>ub(a,b,c,d,25,"touchcancel"),R:(a,b,c,d)=>ub(a,b,c,d,23,"touchend"),S:(a,b,c,d)=>ub(a,b,c,d,24,"touchmove"),T:(a,b,c,d)=>ub(a,b,c,d,22,"touchstart"),L:(a,b,c,d)=>{Mb(a,b,c,d,31,"webglcontextlost");
return 0},K:(a,b,c,d)=>{Mb(a,b,c,d,32,"webglcontextrestored");return 0},X:(a,b,c,d)=>(a=J(a))?"undefined"!=typeof a.onwheel?Nb(a,b,c,d):-1:-4,Za:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Ob[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Qc:u[c+4],yd:u[c+5],Lc:r[b+24],cd:r[b+25],Ad:u[c+7],Ed:r[b+32]};a=J(a);return!a||b.cd?0:Kb(a,b)},Xa:(a,b)=>{a=Eb[a];b=b?A(t,b):"";b.startsWith("GL_")&&
(b=b.substr(3));"ANGLE_instanced_arrays"==b&&vb(P);"OES_vertex_array_object"==b&&wb(P);"WEBGL_draw_buffers"==b&&xb(P);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&yb(P);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&zb(P);"WEBGL_multi_draw"==b&&(P.hd=P.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(P.ed=P.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(P.dd=P.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(P.jd=P.getExtension("WEBGL_polygon_mode"));
return!!a.xc.getExtension(b)},Ya:a=>{Y=Eb[a];f.od=P=Y?.xc;return!a||P?0:-5},Ob:Oa,kb:()=>52,db:function(){return 70},lb:(a,b,c,d)=>{for(var e=0,k=0;k<c;k++){var h=w[b>>2],l=w[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=t[h+m],v=Pb[a];0===p||10===p?((1===a?ma:n)(A(v)),v.length=0):v.push(p)}e+=l}w[d>>2]=e;return 0},m:a=>P.activeTexture(a),ta:(a,b)=>{P.attachShader(R[a],U[b])},b:(a,b)=>{35051==a?P.Jc=b:35052==a&&(P.oc=b);P.bindBuffer(a,Q[b])},a:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},h:(a,b)=>{P.bindFramebuffer(a,
Cb[b])},Fa:(a,b)=>{P.bindRenderbuffer(a,S[b])},l:(a,b)=>{P.bindSampler(a,V[b])},d:(a,b)=>{P.bindTexture(a,T[b])},J:a=>{P.bindVertexArray(Db[a])},F:(a,b,c,d)=>P.blendColor(a,b,c,d),G:(a,b)=>P.blendEquationSeparate(a,b),H:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),rb:(a,b,c,d,e,k,h,l,m,p)=>P.blitFramebuffer(a,b,c,d,e,k,h,l,m,p),Ha:(a,b,c,d)=>{2<=Y.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?t.subarray(c,c+b):b,d)},y:(a,b,c,d)=>{2<=Y.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,
b,t.subarray(d,d+c))},na:a=>P.checkFramebufferStatus(a),Bb:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),ja:(a,b,c)=>{P.clearBufferfv(a,b,sa,c>>2)},Ab:(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},n:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},Gb:a=>{P.compileShader(U[a])},za:(a,b,c,d,e,k,h,l)=>{2<=Y.version?P.oc||!h?P.compressedTexImage2D(a,b,c,d,e,k,h,l):P.compressedTexImage2D(a,b,c,d,e,k,t,l,h):P.compressedTexImage2D(a,b,c,d,e,k,t.subarray(l,l+h))},xa:(a,b,c,d,e,k,h,l,m)=>{P.oc?P.compressedTexImage3D(a,b,c,d,e,k,
h,l,m):P.compressedTexImage3D(a,b,c,d,e,k,h,t,m,l)},ua:()=>{var a=Ib(R),b=P.createProgram();b.name=a;b.vc=b.tc=b.uc=0;b.Gc=1;R[a]=b;return a},Ib:a=>{var b=Ib(U);U[b]=P.createShader(a);return b},C:a=>P.cullFace(a),Ka:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.Jc&&(P.Jc=0),d==P.oc&&(P.oc=0))}},j:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Cb[d];e&&(P.deleteFramebuffer(e),e.name=0,Cb[d]=null)}},p:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),
b.name=0,R[a]=null):W||=1281}},A:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(P.deleteRenderbuffer(e),e.name=0,S[d]=null)}},z:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=V[d];e&&(P.deleteSampler(e),e.name=0,V[d]=null)}},v:a=>{if(a){var b=U[a];b?(P.deleteShader(b),U[a]=null):W||=1281}},B:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=T[d];e&&(P.deleteTexture(e),e.name=0,T[d]=null)}},Ja:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(Db[d]);Db[d]=null}},s:a=>P.depthFunc(a),
r:a=>{P.depthMask(!!a)},e:a=>P.disable(a),I:a=>{P.disableVertexAttribArray(a)},tb:(a,b,c)=>{P.drawArrays(a,b,c)},ub:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},ma:(a,b)=>{for(var c=Qb[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];P.drawBuffers(c)},vb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},wb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},g:a=>P.enable(a),xb:a=>{P.enableVertexAttribArray(a)},oa:(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,S[d])},i:(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,T[d],e)},u:(a,b,c,d,e)=>
{P.framebufferTextureLayer(a,b,T[c],d,e)},D:a=>P.frontFace(a),Ia:(a,b)=>{X(a,b,"createBuffer",Q)},pa:(a,b)=>{X(a,b,"createFramebuffer",Cb)},Ga:(a,b)=>{X(a,b,"createRenderbuffer",S)},va:(a,b)=>{X(a,b,"createSampler",V)},Da:(a,b)=>{X(a,b,"createTexture",T)},Ra:(a,b)=>{X(a,b,"createVertexArray",Db)},Db:(a,b)=>P.getAttribLocation(R[a],b?A(t,b):""),c:(a,b)=>Sb(a,b),Kb:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(u[c>>2]=b)},sa:(a,b,c)=>{if(c)if(a>=Bb)W||=
1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.vc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.vc=Math.max(a.vc,P.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.vc}else if(35722==b){if(!a.tc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.tc=Math.max(a.tc,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.tc}else if(35381==b){if(!a.uc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.uc=Math.max(a.uc,P.getActiveUniformBlockName(a,
b).length+1);u[c>>2]=a.uc}else u[c>>2]=P.getProgramParameter(a,b);else W||=1281},Eb:(a,b,c,d)=>{a=P.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(u[c>>2]=b)},qa:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(U[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(U[a],b):W||=1281},Pa:(a,b)=>{if(2>Y.version)return W||=1282,0;var c=Fb[a];if(c)return 0>b||b>=c.length?(W||=1281,
0):c[b];switch(a){case 7939:return c=Rb().map(Ub),c=Fb[a]=c,0>b||b>=c.length?(W||=1281,0):c[b];default:return W||=1280,0}},ra:(a,b)=>{b=b?A(t,b):"";if(a=R[a]){var c=a,d=c.sc,e=c.$c,k;if(!d){c.sc=d={};c.Zc={};var h=P.getProgramParameter(c,35718);for(k=0;k<h;++k){var l=P.getActiveUniform(c,k);var m=l.name;l=l.size;var p=Vb(m);p=0<p?m.slice(0,p):m;var v=c.Gc;c.Gc+=l;e[p]=[l,v];for(m=0;m<l;++m)d[v]=m,c.Zc[v++]=p}}c=a.sc;d=0;e=b;k=Vb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.$c[e])&&
d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else W||=1281;return-1},qb:(a,b,c)=>{for(var d=Qb[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,d)},Lb:a=>{a=R[a];P.linkProgram(a);a.sc=0;a.$c={}},Qa:(a,b)=>{3317==a?Gb=b:3314==a&&(Hb=b);P.pixelStorei(a,b)},E:(a,b)=>P.polygonOffset(a,b),sb:a=>P.readBuffer(a),Ea:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),w:(a,b,c)=>{P.samplerParameterf(V[a],b,c)},f:(a,b,c)=>{P.samplerParameteri(V[a],b,c)},Cb:(a,b,c,d)=>P.scissor(a,
b,c,d),Hb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var h=(h=w[c+4*k>>2])?A(t,h,d?w[d+4*k>>2]:void 0):"";e+=h}P.shaderSource(U[a],e)},Oa:(a,b,c)=>P.stencilFunc(a,b,c),ia:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),q:a=>P.stencilMask(a),Ma:(a,b,c)=>P.stencilOp(a,b,c),ha:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),ya:(a,b,c,d,e,k,h,l,m)=>{if(2<=Y.version){if(P.oc){P.texImage2D(a,b,c,d,e,k,h,l,m);return}if(m){var p=Wb(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,k,h,l,p,m);return}}p=m?Xb(l,
h,d,e,m):null;P.texImage2D(a,b,c,d,e,k,h,l,p)},wa:(a,b,c,d,e,k,h,l,m,p)=>{if(P.oc)P.texImage3D(a,b,c,d,e,k,h,l,m,p);else if(p){var v=Wb(m);P.texImage3D(a,b,c,d,e,k,h,l,m,v,p>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,k,h,l,m,null)},Ca:(a,b,c)=>P.texParameteri(a,b,c),Ba:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),Aa:(a,b,c,d,e,k)=>P.texStorage3D(a,b,c,d,e,k),pb:(a,b,c,d,e,k,h,l,m)=>{if(2<=Y.version){if(P.oc){P.texSubImage2D(a,b,c,d,e,k,h,l,m);return}if(m){var p=Wb(l);P.texSubImage2D(a,
b,c,d,e,k,h,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}m=m?Xb(l,h,e,k,m):null;P.texSubImage2D(a,b,c,d,e,k,h,l,m)},ob:(a,b,c,d,e,k,h,l,m,p,v)=>{if(P.oc)P.texSubImage3D(a,b,c,d,e,k,h,l,m,p,v);else if(v){var N=Wb(p);P.texSubImage3D(a,b,c,d,e,k,h,l,m,p,N,v>>>31-Math.clz32(N.BYTES_PER_ELEMENT))}else P.texSubImage3D(a,b,c,d,e,k,h,l,m,p,null)},Jb:(a,b)=>{var c=P,d=c.uniform1i;var e=P.bd;if(e){var k=e.sc[a];"number"==typeof k&&(e.sc[a]=k=P.getUniformLocation(e,e.Zc[a]+(0<k?`[${k}]`:"")));a=k}else W||=
1282,a=void 0;d.call(c,a,b)},k:a=>{a=R[a];P.useProgram(a);P.bd=a},yb:(a,b)=>{P.vertexAttribDivisor(a,b)},zb:(a,b,c,d,e,k)=>{P.vertexAttribPointer(a,b,c,!!d,e,k)},ka:(a,b,c,d)=>P.viewport(a,b,c,d),eb:Na,Nb:function(){f.Tc=a=>{0!=ec()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Tc)},Wa:function(){f.Yc=a=>{const b=a.clipboardData.getData("text");bc(()=>{const c=Zb(b);fc(c)})};window.addEventListener("paste",f.Yc)},Sa:function(a){f.Gd=[];a=a?A(t,a):"";a=document.getElementById(a);
f.Uc=b=>{b.stopPropagation();b.preventDefault()};f.Vc=b=>{b.stopPropagation();b.preventDefault()};f.Wc=b=>{b.stopPropagation();b.preventDefault()};f.Xc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Hd=c;gc(c.length);for(let e=0;e<c.length;e++)bc(()=>{const k=Zb(c[e].name);hc(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ic(b.clientX,b.clientY,d)};a.addEventListener("dragenter",f.Uc,!1);a.addEventListener("dragleave",f.Vc,!1);a.addEventListener("dragover",
f.Wc,!1);a.addEventListener("drop",f.Xc,!1)},Mb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},x:function(){document.exitPointerLock&&document.exitPointerLock()},La:function(a){a=a?A(t,a):"";f.rc=document.getElementById(a);f.rc||console.log("sokol_app.h: invalid target:"+a);f.rc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},ab:function(){window.removeEventListener("beforeunload",f.Tc)},Va:function(){window.removeEventListener("paste",
f.Yc)},Na:function(a){a=a?A(t,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",f.Uc);a.removeEventListener("dragleave",f.Vc);a.removeEventListener("dragover",f.Wc);a.removeEventListener("drop",f.Xc)},o:function(){f.rc&&f.rc.requestPointerLock&&f.rc.requestPointerLock()},Fb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(t.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},bb:function(){return f.nc?f.nc.bufferSize:0},mb:function(a,b,c){f.hc=null;f.nc=null;"undefined"!==typeof AudioContext?f.hc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.hc=null,console.log("sokol_audio.h: no WebAudio support"));return f.hc?(console.log("sokol_audio.h: sample rate ",f.hc.sampleRate),f.nc=f.hc.createScriptProcessor(c,0,b),f.nc.onaudioprocess=d=>{const e=d.outputBuffer.length,
k=jc(e);if(k){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=sa[(k>>2)+(h*p+l)]}}},f.nc.connect(f.hc.destination),a=()=>{f.hc&&"suspended"===f.hc.state&&f.hc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},cb:function(){return f.hc?f.hc.sampleRate:0},ga:function(){const a=f.hc;null!==a&&(f.nc&&f.nc.disconnect(),
a.close(),f.hc=null,f.nc=null)},t:function(a,b,c,d,e,k){b=b?A(t,b):"";const h=new XMLHttpRequest;h.open("GET",b);h.responseType="arraybuffer";const l=0<d;l&&h.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));h.onreadystatechange=function(){if(h.readyState==XMLHttpRequest.DONE)if(206==h.status||200==h.status&&!l){const m=new Uint8Array(h.response),p=m.length;p<=k?(t.set(m,e),kc(a,d,p)):lc(a)}else mc(a,h.status)};h.send()},la:function(a,b){b=b?A(t,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=
function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");nc(a,d)}else mc(a,c.status)};c.send()},fa:function(a,b){b=b?A(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;oa=Z.Pb;ta();nb=Z.cc;va.unshift(Z.Qb);y--;f.monitorRunDependencies?.(y);0==y&&(null!==za&&(clearInterval(za),za=null),z&&(c=z,z=null,c()));return Z}var b=
{a:oc};y++;f.monitorRunDependencies?.(y);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return n(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ca??=Ba("doom.wasm")?"doom.wasm":f.locateFile?f.locateFile("doom.wasm",g):g+"doom.wasm";Ga(b,function(c){a(c.instance)});return{}}(),M=a=>(M=Z.Rb)(a),fc=f.__sapp_emsc_onpaste=a=>(fc=f.__sapp_emsc_onpaste=Z.Sb)(a),ec=f.__sapp_html5_get_ask_leave_site=()=>(ec=f.__sapp_html5_get_ask_leave_site=Z.Tb)(),gc=f.__sapp_emsc_begin_drop=
a=>(gc=f.__sapp_emsc_begin_drop=Z.Ub)(a),hc=f.__sapp_emsc_drop=(a,b)=>(hc=f.__sapp_emsc_drop=Z.Vb)(a,b),ic=f.__sapp_emsc_end_drop=(a,b,c)=>(ic=f.__sapp_emsc_end_drop=Z.Wb)(a,b,c);f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,h,l)=>(f.__sapp_emsc_invoke_fetch_cb=Z.Xb)(a,b,c,d,e,k,h,l);
var pc=f._main=(a,b)=>(pc=f._main=Z.Yb)(a,b),nc=f.__sfetch_emsc_head_response=(a,b)=>(nc=f.__sfetch_emsc_head_response=Z.Zb)(a,b),kc=f.__sfetch_emsc_get_response=(a,b,c)=>(kc=f.__sfetch_emsc_get_response=Z._b)(a,b,c),mc=f.__sfetch_emsc_failed_http_status=(a,b)=>(mc=f.__sfetch_emsc_failed_http_status=Z.$b)(a,b),lc=f.__sfetch_emsc_failed_buffer_too_small=a=>(lc=f.__sfetch_emsc_failed_buffer_too_small=Z.ac)(a),jc=f.__saudio_emsc_pull=a=>(jc=f.__saudio_emsc_pull=Z.bc)(a),dc=(a,b)=>(dc=Z.dc)(a,b),ac=a=>
(ac=Z.ec)(a),Yb=a=>(Yb=Z.fc)(a),$b=()=>($b=Z.gc)(),qc;z=function rc(){qc||sc();qc||(z=rc)};function tc(a=[]){var b=pc;a.unshift(fa);var c=a.length,d=Yb(4*(c+1)),e=d;a.forEach(h=>{w[e>>2]=Zb(h);e+=4});w[e>>2]=0;try{var k=b(c,d);Oa(k,!0)}catch(h){Ma(h)}}
function sc(){var a=ea;function b(){if(!qc&&(qc=!0,f.calledRun=!0,!q)){Ia(va);Ia(wa);f.onRuntimeInitialized?.();uc&&tc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();xa.unshift(c)}Ia(xa)}}if(!(0<y)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();Ia(ua);0<y||(f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var uc=!0;f.noInitialRun&&(uc=!1);sc();
